language: python
python:
 - "2.7"
install: pip install pika PyYAML
#services: # enable once I get the testing sorted
# - rabbitmq
script:
 - python -m py_compile lbupdate.py
 - python -m py_compile lbupdate-agent.py
